
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package practica1comp2.backend.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISTINTO = 25;
  public static final int POR = 12;
  public static final int CHAR = 3;
  public static final int PT_COMA = 31;
  public static final int ELSIF = 40;
  public static final int DOUBLE = 8;
  public static final int INT = 5;
  public static final int PRINTLN = 45;
  public static final int ARRAY = 37;
  public static final int FOR = 43;
  public static final int IDENTIFICADOR = 36;
  public static final int NOT = 15;
  public static final int AND = 16;
  public static final int IGUAL = 24;
  public static final int OR = 17;
  public static final int DIV = 13;
  public static final int PARENT_C = 27;
  public static final int IF = 38;
  public static final int PARENT_A = 26;
  public static final int NUMERO_FLOTANTE = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int TRUE = 18;
  public static final int DOS_PT = 32;
  public static final int error = 1;
  public static final int MAYOR_I = 22;
  public static final int COMA = 30;
  public static final int CADENA = 46;
  public static final int MENOS = 11;
  public static final int MENOR = 21;
  public static final int MOD = 14;
  public static final int MENOR_I = 23;
  public static final int BYTE = 4;
  public static final int MAYOR = 20;
  public static final int ELSE = 39;
  public static final int WHILE = 41;
  public static final int FLOAT = 7;
  public static final int ASIGN = 33;
  public static final int LONG = 6;
  public static final int STRING = 9;
  public static final int FALSE = 19;
  public static final int CORCH_C = 29;
  public static final int NUMERO_ENTERO = 34;
  public static final int CORCH_A = 28;
  public static final int PRINT = 44;
  public static final int DO = 42;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOLEAN",
  "CHAR",
  "BYTE",
  "INT",
  "LONG",
  "FLOAT",
  "DOUBLE",
  "STRING",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "NOT",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "MAYOR",
  "MENOR",
  "MAYOR_I",
  "MENOR_I",
  "IGUAL",
  "DISTINTO",
  "PARENT_A",
  "PARENT_C",
  "CORCH_A",
  "CORCH_C",
  "COMA",
  "PT_COMA",
  "DOS_PT",
  "ASIGN",
  "NUMERO_ENTERO",
  "NUMERO_FLOTANTE",
  "IDENTIFICADOR",
  "ARRAY",
  "IF",
  "ELSE",
  "ELSIF",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "PRINTLN",
  "CADENA"
  };
}

