/*
 * Frame Principal
 */
package practica2compi1.frontend;

import javax.swing.JFrame;
/**
 *
 * @author bryan
 */
public class FramePrincipal extends javax.swing.JFrame {
    private PanelGrafico contentPane;
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        
        //initComponents();
        
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(800, 500);
        contentPane = new PanelGrafico(this);
        
        
        
        add(contentPane);
        
//        
//        contentPane.agregarLinea(200, 200, 200, 500);
//        contentPane.agregarLinea(210, 200, 210, 500);
//        contentPane.agregarLinea(220, 200, 220, 500);
//        contentPane.agregarLinea(230, 200, 230, 500);
//        contentPane.agregarLinea(240, 200, 240, 500);
//        contentPane.agregarLinea(250, 200, 250, 500);
//        contentPane.rep();
//        
//        contentPane.agregarLinea(300, 300, 300, 500);
//        contentPane.agregarLinea(310, 300, 310, 500);
//        contentPane.agregarLinea(320, 300, 320, 500);
//        contentPane.agregarLinea(330, 300, 330, 500);
//        contentPane.agregarLinea(340, 300, 340, 500);
//        contentPane.agregarLinea(350, 300, 350, 500);
//        contentPane.rep();
//        contentPane = new JPanel();
//        contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
//        contentPane.setBackground(Color.GREEN);
//        contentPane.setSize(780, 200);
//        //setContentPane(contentPane);
//        contentPane.setLayout(null);
//        add(contentPane);
//        //repaint();
//        contentPane2 = new JPanel();
//        contentPane2.setBorder(new EmptyBorder(5, 5, 5, 5));
//        //setContentPane(contentPane2);
//        contentPane2.setBackground(Color.BLUE);
//        contentPane2.setSize(780, 200);
//        contentPane2.setLayout(null);
//        add(contentPane2);
        //setLocationRelativeTo(null);
        
        
        
    }
    
    public void paintComponent(){
            
    }
    
//    @Override
//    public void paint(Graphics g){
//            super.paint(g);
//            g.setColor(Color.blue);
//            g.drawRect(30,80,100,140); 
//            g.setColor(Color.red);
//            g.drawLine(30,80,130,80);
//            g.drawLine(30,220,130,220);
//         
//    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KOK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
