
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 28 20:26:29 CST 2019
//----------------------------------------------------

package practica2compi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IGUAL = 2;
  public static final int POSITION_XY = 23;
  public static final int COMENTARIO_LINEA = 13;
  public static final int SUMA = 7;
  public static final int COLOR = 22;
  public static final int CODIGO_COLOR = 32;
  public static final int VARIABLE = 31;
  public static final int NUMERO_ENTERO = 33;
  public static final int TO_ERASE = 28;
  public static final int BACKWARD = 15;
  public static final int RIGHT = 16;
  public static final int FORWARD = 14;
  public static final int COMA = 11;
  public static final int TO_DRAW = 29;
  public static final int LEFT = 17;
  public static final int POSITION_Y = 25;
  public static final int EOF = 0;
  public static final int MULT = 9;
  public static final int POSITION_X = 24;
  public static final int PEN_UP = 19;
  public static final int DIV = 10;
  public static final int SHOW_TURTLE = 27;
  public static final int TO_CENTER = 21;
  public static final int error = 1;
  public static final int HIDE_TURTLE = 26;
  public static final int PARENT_C = 6;
  public static final int PEN_DOWN = 20;
  public static final int CLEARS = 18;
  public static final int PARENT_A = 5;
  public static final int SALTO = 12;
  public static final int CORCHETE_C = 4;
  public static final int REPEAT = 30;
  public static final int CORCHETE_A = 3;
  public static final int RESTA = 8;
}

