/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresarial.gui.frames;

import empresarial.backend.recursoshumanos.ManejadorRH;
import empresarial.gui.frames.recursoshumanos.ListadoEmpleadosFrame;
import java.awt.Toolkit;

/**
 *
 * @author jose
 */
public class EscritorioFrame extends javax.swing.JFrame {

	private ManejadorRH manejador;
	private ListadoEmpleadosFrame listadoEmpleadosFrame;
	/**
	 * Creates new form EscritorioFrame
	 */
	public EscritorioFrame(ManejadorRH manejador) {
		initComponents();
		this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
		this.manejador = manejador;
		this.listadoEmpleadosFrame = new ListadoEmpleadosFrame(manejador);
		this.escritorioPanel.add(listadoEmpleadosFrame);
		setIcon();
		
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          escritorioPanel = new javax.swing.JDesktopPane();
          jMenuBar1 = new javax.swing.JMenuBar();
          jMenu1 = new javax.swing.JMenu();
          jMenuItem1 = new javax.swing.JMenuItem();
          jMenu2 = new javax.swing.JMenu();
          jMenuItem2 = new javax.swing.JMenuItem();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Aplicacion Empresarial");

          javax.swing.GroupLayout escritorioPanelLayout = new javax.swing.GroupLayout(escritorioPanel);
          escritorioPanel.setLayout(escritorioPanelLayout);
          escritorioPanelLayout.setHorizontalGroup(
               escritorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 400, Short.MAX_VALUE)
          );
          escritorioPanelLayout.setVerticalGroup(
               escritorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 279, Short.MAX_VALUE)
          );

          jMenu1.setText("Archivo");

          jMenuItem1.setText("Salir");
          jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem1ActionPerformed(evt);
               }
          });
          jMenu1.add(jMenuItem1);

          jMenuBar1.add(jMenu1);

          jMenu2.setText("Empleados");

          jMenuItem2.setText("Ver Empleados");
          jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem2ActionPerformed(evt);
               }
          });
          jMenu2.add(jMenuItem2);

          jMenuBar1.add(jMenu2);

          setJMenuBar(jMenuBar1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(escritorioPanel)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(escritorioPanel)
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          // TODO add your handling code here:
		this.dispose();
     }//GEN-LAST:event_jMenuItem1ActionPerformed

     private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          // TODO add your handling code here:
		this.listadoEmpleadosFrame.setVisible(true);
     }//GEN-LAST:event_jMenuItem2ActionPerformed

	private void setIcon() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/empresarial/imagenes/icon.png")));
	}
	
     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JDesktopPane escritorioPanel;
     private javax.swing.JMenu jMenu1;
     private javax.swing.JMenu jMenu2;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JMenuItem jMenuItem1;
     private javax.swing.JMenuItem jMenuItem2;
     // End of variables declaration//GEN-END:variables
}
