/*
 * Aplicacion de Clientes
 */
package proyecto2ipc2.frontend;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import proyecto2ipc2.backend.User.Logger;
import proyecto2ipc2.frontend.Forms.FormCRUDHabitacion;
import proyecto2ipc2.frontend.Forms.FormCRUDReservacion;
import proyecto2ipc2.frontend.Forms.FormValoracionHabitacion;
import proyecto2ipc2.frontend.Forms.FormValoracionRestaurante;

/**
 *
 * @author bryan
 */
public class AplicacionClientes extends javax.swing.JFrame {
    public static LocalDate fechaActual;
    /**
     * Creates new form AplicacionClientes
     */
    public AplicacionClientes() {
        initComponents();
        this.asignarLogger();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorioTrabajo = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicacion Clientes");

        escritorioTrabajo.setBackground(new java.awt.Color(204, 255, 204));
        escritorioTrabajo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout escritorioTrabajoLayout = new javax.swing.GroupLayout(escritorioTrabajo);
        escritorioTrabajo.setLayout(escritorioTrabajoLayout);
        escritorioTrabajoLayout.setHorizontalGroup(
            escritorioTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );
        escritorioTrabajoLayout.setVerticalGroup(
            escritorioTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jMenu1.setText("Reservaciones");

        jMenuItem1.setText("Reservar una Habitacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opiniones");

        jMenuItem2.setText("Sobre Habitaciones de Hotel");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Sobre Platillos de Restaurante");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Salir");

        jMenuItem4.setText("Cerrar Aplicacion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioTrabajo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorioTrabajo)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
            this.formOpinionHabitacion= new FormValoracionHabitacion(this);
            //agregando al panel de escritorio
            this.escritorioTrabajo.add(this.formOpinionHabitacion);
            this.formOpinionHabitacion.show();//visualizando
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
            this.formOpinionMenu= new FormValoracionRestaurante(this);
            //agregando al panel de escritorio
            this.escritorioTrabajo.add(this.formOpinionMenu);
            this.formOpinionMenu.show();//visualizando
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
            System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
            this.formReservacion= new FormCRUDReservacion(null);
            //agregando al panel de escritorio
            this.escritorioTrabajo.add(this.formReservacion);
            formReservacion.deshabilitarBotonesParaClientes();
            this.formReservacion.show();//visualizando
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void asignarLogger(){
            Logger logger= Logger.getInstance();
            logger.setUser("Cliente");
            logger.setEstablecimiento(null);
            logger.setIdEstablecimiento(0);
            
    }
    public static  String fechaActualDelSistema(){//metodo que devuelve fecha actual en el sistema
                fechaActual= LocalDate.now();
                //Convirtiendolo a String
                String date = fechaActual.format(DateTimeFormatter.ofPattern("yyyy/MM/dd"));  
                return date;
    }
    public static  String fechaActualDelSistema2(){//metodo que devuelve fecha actual en el sistema
            fechaActual= LocalDate.now();
            //Convirtiendolo a String
            String date = fechaActual.format(DateTimeFormatter.ofPattern("dd/MM/yyyy"));  
            return date;
    }
    private FormCRUDReservacion formReservacion;
    private FormCRUDHabitacion formHabitacion;
    private FormValoracionHabitacion formOpinionHabitacion;
    private FormValoracionRestaurante formOpinionMenu;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorioTrabajo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
