
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 25 02:01:18 CST 2019
//----------------------------------------------------

package proyecto2compi1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFICADOR = 74;
  public static final int AMP_OACUTE = 27;
  public static final int AMP_LT = 21;
  public static final int MENOR_IGUAL = 18;
  public static final int AMP = 23;
  public static final int TYPE = 60;
  public static final int AMP_IACUTE = 26;
  public static final int BGCOLOR = 53;
  public static final int ANCLA_ETIQUETA = 70;
  public static final int AMP_NTILDE_MAYUS = 29;
  public static final int NAME = 63;
  public static final int CONST_COLOR = 65;
  public static final int TEXTO = 71;
  public static final int NUMERO_ENTERO = 73;
  public static final int SUP = 43;
  public static final int DIFERENTE = 20;
  public static final int BLINK = 41;
  public static final int PARENT_C = 6;
  public static final int PARENT_A = 5;
  public static final int INTEGER = 76;
  public static final int PARAMETRO_TEXTO = 72;
  public static final int SUB = 42;
  public static final int FONT = 44;
  public static final int LI = 47;
  public static final int FALSE = 80;
  public static final int CENTER = 35;
  public static final int CORCHETE_C = 4;
  public static final int CORCHETE_A = 3;
  public static final int TEXT = 54;
  public static final int VAR = 75;
  public static final int THEN = 85;
  public static final int PT_COMA = 17;
  public static final int CIERRA = 13;
  public static final int HTML = 31;
  public static final int WIDTH = 62;
  public static final int STRIKE = 40;
  public static final int NOBR = 49;
  public static final int COMA = 11;
  public static final int AMP_EACUTE = 25;
  public static final int TRUE = 79;
  public static final int IGUAL = 2;
  public static final int WHILE = 86;
  public static final int PORCENTAJE = 69;
  public static final int ALIGN = 56;
  public static final int DOS_PT_IGUAL = 16;
  public static final int BOOLEAN = 77;
  public static final int FIN = 10;
  public static final int FOR = 87;
  public static final int FACE = 58;
  public static final int DOS_PT = 15;
  public static final int U = 38;
  public static final int MULT = 9;
  public static final int P = 36;
  public static final int ELSE = 84;
  public static final int CIERRA_EMBE = 93;
  public static final int I = 39;
  public static final int LINK = 55;
  public static final int EOF = 0;
  public static final int B = 37;
  public static final int A = 52;
  public static final int AMP_NTILDE_MINUS = 30;
  public static final int SUMA = 7;
  public static final int COM = 14;
  public static final int PRINT = 89;
  public static final int BLOCKQUOTE = 51;
  public static final int TIPO_LISTA = 68;
  public static final int BODY = 34;
  public static final int HREF = 64;
  public static final int TITLE = 33;
  public static final int OR = 82;
  public static final int error = 1;
  public static final int START = 61;
  public static final int RESTA = 8;
  public static final int OL = 46;
  public static final int IF = 83;
  public static final int COLOR = 59;
  public static final int UL = 45;
  public static final int HEAD = 32;
  public static final int END = 91;
  public static final int AMP_AACUTE = 24;
  public static final int AMP_GT = 22;
  public static final int ABRE_EMBE = 92;
  public static final int BR = 48;
  public static final int BEGIN = 90;
  public static final int HR = 50;
  public static final int STRING = 78;
  public static final int SIZE = 57;
  public static final int ALINEACION = 66;
  public static final int TIPO_LETRA = 67;
  public static final int AND = 81;
  public static final int TO = 88;
  public static final int ABRE = 12;
  public static final int AMP_UACUTE = 28;
  public static final int MAYOR_IGUAL = 19;
}

