/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc2.frontend.Forms;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto2ipc2.backend.Restaurante.ControladorRestaurantes;
import proyecto2ipc2.backend.Restaurante.Restaurante;
import proyecto2ipc2.backend.User.ControladorUsuarios;

/**
 *
 * @author bryan
 */
public class AsignacionRestaurante extends javax.swing.JDialog {
    private String usuario;
    private String cargo;
    private ControladorRestaurantes controladorRestaurantes;
    private ControladorUsuarios controladorUsuarios;
    /**
     * Creates new form AsignacionRestaurante
     */
    public AsignacionRestaurante(java.awt.Frame parent,String usuario,String cargo) {
        super(parent, true);
        this.usuario= usuario;
        this.cargo=cargo;
        
        initComponents();
        this.txtUsuario.setText(usuario);
        this.txtCargo.setText(cargo);
        cargarTablaRestaurantes();
        verificarAsignacion();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombreRestaurante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdRestaurante = new javax.swing.JTextField();
        btnAsignar = new javax.swing.JButton();
        btnDesasignar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRestaurantes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();
        lbAlerta = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignacion de Empleados de Restaurante");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Usuario:");

        txtUsuario.setEditable(false);

        jLabel2.setText("Restaurante:");

        txtNombreRestaurante.setEditable(false);

        jLabel3.setText("ID:");

        txtIdRestaurante.setEditable(false);

        btnAsignar.setBackground(new java.awt.Color(0, 51, 255));
        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setText("Asignar Usuario");
        btnAsignar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnDesasignar.setBackground(new java.awt.Color(255, 0, 0));
        btnDesasignar.setForeground(new java.awt.Color(255, 255, 255));
        btnDesasignar.setText("Desasignar Usuario");
        btnDesasignar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesasignarActionPerformed(evt);
            }
        });

        tbRestaurantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRestaurantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRestaurantesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbRestaurantes);

        jLabel4.setText("Cargo:");

        txtCargo.setEditable(false);

        lbAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lbAlerta.setText("Este Usuario actualmente esta Asignado");

        jLabel5.setText("Restaurantes Disponibles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesasignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbAlerta)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsuario)
                                .addComponent(txtNombreRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                .addComponent(txtCargo)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(20, 20, 20)
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesasignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAlerta)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbRestaurantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRestaurantesMouseClicked
        // TODO add your handling code here:
            DefaultTableModel model =(DefaultTableModel)tbRestaurantes.getModel();
            
            if(tbRestaurantes.getSelectedRow()!=-1){//si se ha seleccionado algo en la tabla se rellenan los campo
                    txtIdRestaurante.setText(model.getValueAt(tbRestaurantes.getSelectedRow(), 0).toString());
                    txtNombreRestaurante.setText(model.getValueAt(tbRestaurantes.getSelectedRow(), 1).toString());
                   
            }
    }//GEN-LAST:event_tbRestaurantesMouseClicked

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
            if (txtIdRestaurante.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null,"Seleccione primero un Restaurante", "Error de Asignacion", JOptionPane.ERROR_MESSAGE);
            } else {
                        controladorUsuarios= new ControladorUsuarios();
                        controladorUsuarios.asignarRestaurante(usuario, Integer.parseInt(txtIdRestaurante.getText()));
                        btnAsignar.setEnabled(false);
                        btnDesasignar.setEnabled(true);
                        lbAlerta.setVisible(true);

            }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnDesasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesasignarActionPerformed
        // TODO add your handling code here:
            controladorUsuarios= new ControladorUsuarios();
            controladorUsuarios.desasignarRestaurante(usuario);
            btnAsignar.setEnabled(true);
            btnDesasignar.setEnabled(false);
            lbAlerta.setVisible(false);
    }//GEN-LAST:event_btnDesasignarActionPerformed
    public void cargarTablaRestaurantes(){
            controladorRestaurantes= new ControladorRestaurantes();
            List<Restaurante> lista= controladorRestaurantes.recuperarRestaurantes();
            DefaultTableModel model= (DefaultTableModel)this.tbRestaurantes.getModel();
            for(Restaurante restaurante: lista){
                    model.addRow(new Object[]{restaurante.getId(),restaurante.getNombre(),restaurante.getDireccion()});
            }                
    }
    public void verificarAsignacion(){
            controladorUsuarios= new ControladorUsuarios();
            if (controladorUsuarios.consultarRestAsignado(usuario)==null) {
                    btnAsignar.setEnabled(true);
                    btnDesasignar.setEnabled(false);
                    lbAlerta.setVisible(false);
            } else {
                        btnAsignar.setEnabled(false);
                        btnDesasignar.setEnabled(true);
                        lbAlerta.setVisible(true);
                }
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnDesasignar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAlerta;
    private javax.swing.JTable tbRestaurantes;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtIdRestaurante;
    private javax.swing.JTextField txtNombreRestaurante;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
