/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto2ipc2.frontend.Forms;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import proyecto2ipc2.backend.Hotel.Cliente;
import proyecto2ipc2.backend.Hotel.ControladorClientes;
import proyecto2ipc2.backend.Hotel.ControladorHabitaciones;
import proyecto2ipc2.backend.Hotel.Habitacion;
import proyecto2ipc2.backend.Hotel.Hotel;
import proyecto2ipc2.backend.Hotel.ValoracionHabitacion;
import proyecto2ipc2.backend.User.Logger;
import static proyecto2ipc2.database.OperadorEsquema.CAMPOS_OBLIGATORIOS;
import static proyecto2ipc2.database.OperadorEsquema.ERROR_CREACION;
import static proyecto2ipc2.database.OperadorEsquema.GUARDAR_DATOS;
import proyecto2ipc2.frontend.AplicacionClientes;

/**
 *
 * @author bryan
 */
public class FormValoracionHabitacion extends javax.swing.JInternalFrame {
    private ControladorHabitaciones controladorHabitaciones;
    private ControladorClientes controladorClientes;
    private Cliente cliente;
    private Habitacion habitacion;
    private Hotel hotel;
    private ValoracionHabitacion valoracion;
    private int idHabitacion;
    private AplicacionClientes ventana;
    /**
     * Creates new form FormValoracionHabitacion1
     */
    public FormValoracionHabitacion(AplicacionClientes ventana) {
        this.ventana= ventana;
        this.idHabitacion=0;
        initComponents();
        this.txtFecha.setText(ventana.fechaActualDelSistema2());
        this.cargarComboHoteles();
        this.cargarComboClientes();
        this.deshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboTipo = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        comboHoteles = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIdHotel = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        comboNits = new javax.swing.JComboBox<>();
        lbNumeroEstrellas = new javax.swing.JLabel();
        comboNumeroEstrellas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHabitaciones = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Opiniones sobre Habitaciones");

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Numero:*");

        txtNumero.setEditable(false);

        jLabel3.setText("Tipo:  *");

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitacion_Junior", "Habitacion_Master", "Habitacion_De_Lujo" }));

        btnLimpiar.setText("Limpiar Campos");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        comboHoteles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHotelesActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre del Hotel:");

        jLabel9.setText("ID:");

        txtIdHotel.setEditable(false);

        btnRegistrar.setText("Registrar mi Opinion");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel10.setText("Cliente: *");

        jLabel11.setText("NIT: *");

        txtNombreCliente.setEditable(false);

        comboNits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNitsActionPerformed(evt);
            }
        });

        lbNumeroEstrellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto2ipc2/frontend/img/estrella1.gif"))); // NOI18N
        lbNumeroEstrellas.setText("No. Estrellas:*");

        comboNumeroEstrellas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        jLabel4.setText("Comentario: ");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane2.setViewportView(txtComentario);

        jLabel2.setText("Fecha:");

        txtFecha.setEditable(false);
        try {
            txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboHoteles, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(14, 14, 14)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboTipo, 0, 182, Short.MAX_VALUE)
                                    .addComponent(txtNumero)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdHotel)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCliente)
                            .addComponent(comboNits, 0, 176, Short.MAX_VALUE)
                            .addComponent(txtFecha))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbNumeroEstrellas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboNumeroEstrellas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNumeroEstrellas)
                    .addComponent(comboNumeroEstrellas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(comboNits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnLimpiar))
                .addGap(12, 12, 12))
        );

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbHabitaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.Habitacion", "Tipo", "Nivel", "Precio", "Estado", "Costo de Mant."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHabitaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHabitacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHabitaciones);

        jLabel6.setText("Listado de Habitaciones (Seleccione una)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void comboHotelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHotelesActionPerformed
        // TODO add your handling code here:
            controladorHabitaciones= new ControladorHabitaciones();

            Logger logger = Logger.getInstance();
            if (logger.getEstablecimiento()!=null) {
                    txtIdHotel.setText(""+logger.getIdEstablecimiento());
                    cargarTablaHabitaciones();
                    deshabilitarComboHoteles();
            } else {
                        txtIdHotel.setText(""+controladorHabitaciones.recuperarHotel((String)comboHoteles.getSelectedItem()));
                        cargarTablaHabitaciones();
            }
    }//GEN-LAST:event_comboHotelesActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
            if (txtNumero.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, CAMPOS_OBLIGATORIOS, ERROR_CREACION, JOptionPane.ERROR_MESSAGE);
            } else {
                        int opcion= JOptionPane.showConfirmDialog(this, GUARDAR_DATOS);
                        if (opcion==0) {
                                LocalDate fecha = LocalDate.parse(ventana.fechaActualDelSistema(), DateTimeFormatter.ofPattern("yyyy/MM/dd"));
                                cliente= new Cliente((String)comboNits.getSelectedItem());
                                habitacion= new Habitacion(Integer.parseInt(txtNumero.getText()));
                                hotel= new Hotel(Integer.parseInt(txtIdHotel.getText()));
                                
                                valoracion= new ValoracionHabitacion((Integer.parseInt((String)comboNumeroEstrellas.getSelectedItem())),
                                                txtComentario.getText(), fecha, cliente, habitacion, hotel);
                                
                                controladorHabitaciones= new ControladorHabitaciones(valoracion, this);
                                controladorHabitaciones.registrarPuntuacionHabitacion();

                        }
                        if(opcion==1){
                                limpiarCampos();
                                deshabilitarBotones();

                        }
            }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void comboNitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNitsActionPerformed
        // TODO add your handling code here:
        controladorClientes = new ControladorClientes();
        Cliente cliente=controladorClientes.recuperarClienteNit((String)comboNits.getSelectedItem());
        if (cliente!=null) {
            txtNombreCliente.setText(cliente.getNombre());
        }
    }//GEN-LAST:event_comboNitsActionPerformed

    private void tbHabitacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHabitacionesMouseClicked
        // TODO add your handling code here:
            habilitarBotones();
            DefaultTableModel model =(DefaultTableModel)tbHabitaciones.getModel();

            if(tbHabitaciones.getSelectedRow()!=-1){//si se ha seleccionado algo en la tabla se rellenan los campo
                    txtNumero.setText(model.getValueAt(tbHabitaciones.getSelectedRow(), 0).toString());
                    comboTipo.setSelectedItem(model.getValueAt(tbHabitaciones.getSelectedRow(), 1));
                    //almacenamos el usuario temporal seleccionado
                    idHabitacion= Integer.parseInt(model.getValueAt(tbHabitaciones.getSelectedRow(), 0).toString());

            }
    }//GEN-LAST:event_tbHabitacionesMouseClicked
    

    public void cargarTablaHabitaciones(){
            limpiarTabla();
            controladorHabitaciones= new ControladorHabitaciones();
            List<Habitacion> lista= controladorHabitaciones.recuperarHabitaciones(Integer.parseInt(txtIdHotel.getText()));
            DefaultTableModel model= (DefaultTableModel)this.tbHabitaciones.getModel();
            for(Habitacion habitacion: lista){
                    model.addRow(new Object[]{habitacion.getNumero(),habitacion.getTipo(),
                    habitacion.getNivel(),habitacion.getPrecio(),habitacion.getEstado(),habitacion.getCostoMant()});
            }                        
    }
    //metodo para limpiar tablas
    public void limpiarTabla(){
            DefaultTableModel tb = (DefaultTableModel)tbHabitaciones.getModel();
            int a = tbHabitaciones.getRowCount()-1;
            for (int i = a; i >= 0; i--) {          
                    tb.removeRow(tb.getRowCount()-1);
            }
    }
    public void cargarComboHoteles(){
            controladorHabitaciones= new ControladorHabitaciones();
            List<Hotel> lista= controladorHabitaciones.recuperarHoteles();
            DefaultComboBoxModel modelComboRestaurantes=(DefaultComboBoxModel)comboHoteles.getModel();
            for(Hotel hotel: lista){
                modelComboRestaurantes.addElement(hotel.getNombre());
            }   AutoCompleteDecorator.decorate(comboHoteles);
    }
    public void cargarComboClientes(){
            controladorClientes= new ControladorClientes();
            List<Cliente> lista= controladorClientes.recuperarClientes();
            DefaultComboBoxModel model4=(DefaultComboBoxModel)comboNits.getModel();
            for(Cliente huesped: lista){
                model4.addElement(huesped.getNit());
            }   AutoCompleteDecorator.decorate(comboNits);
    }
    public void limpiarCampos(){
            txtNumero.setText("");
            txtComentario.setText("");
            comboTipo.setSelectedIndex(0);
            comboHoteles.setSelectedIndex(0);
            comboNits.setSelectedIndex(0);
            comboNumeroEstrellas.setSelectedIndex(0);
    } 
    public void organizarFormulario(){
            limpiarCampos();
            deshabilitarBotones();
    }
    public void seleccionarHotel(String hotel){
            comboHoteles.setSelectedItem(hotel);
    }
    public void deshabilitarComboHoteles(){
            comboHoteles.setEnabled(false);
    }
     public void deshabilitarBotones(){
            btnRegistrar.setEnabled(false);
            
    } 
    public void habilitarBotones(){
            btnRegistrar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboHoteles;
    private javax.swing.JComboBox<String> comboNits;
    private javax.swing.JComboBox<String> comboNumeroEstrellas;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNumeroEstrellas;
    private javax.swing.JTable tbHabitaciones;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtIdHotel;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
