
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 27 01:20:53 CST 2019
//----------------------------------------------------

package consolaLinux;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int EXIT = 22;
  public static final int ENCADENACION = 21;
  public static final int CHMOD = 20;
  public static final int CP = 17;
  public static final int LS = 12;
  public static final int REMOVER_PERMISOS_CHMOD = 9;
  public static final int AGREGAR_PERMISOS_CHMOD = 10;
  public static final int RM = 18;
  public static final int GUION_R_MAYUS = 8;
  public static final int CD = 13;
  public static final int MV = 16;
  public static final int MKDIR = 15;
  public static final int GUION_R_MINUS = 7;
  public static final int PWD = 11;
  public static final int PATH_PADRE = 3;
  public static final int EOF = 0;
  public static final int COMPLET_LS = 6;
  public static final int error = 1;
  public static final int RMDIR = 19;
  public static final int SALTO = 5;
  public static final int ESPACIO = 4;
  public static final int TOUCH = 14;
  public static final int PATH = 2;
}

