package proyectomayaprueba.Modelo;
// Generated 11/09/2019 02:29:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CuentaLarga generated by hbm2java
 */
public class CuentaLarga  implements java.io.Serializable {


     private int idCuantaLarga;
     private GlifoG glifoG;
     private KinCholqij kinCholqij;
     private KinHaab kinHaab;
     private Set hechoHistoricos = new HashSet(0);

    public CuentaLarga() {
    }

	
    public CuentaLarga(int idCuantaLarga, GlifoG glifoG, KinCholqij kinCholqij, KinHaab kinHaab) {
        this.idCuantaLarga = idCuantaLarga;
        this.glifoG = glifoG;
        this.kinCholqij = kinCholqij;
        this.kinHaab = kinHaab;
    }
    public CuentaLarga(int idCuantaLarga, GlifoG glifoG, KinCholqij kinCholqij, KinHaab kinHaab, Set hechoHistoricos) {
       this.idCuantaLarga = idCuantaLarga;
       this.glifoG = glifoG;
       this.kinCholqij = kinCholqij;
       this.kinHaab = kinHaab;
       this.hechoHistoricos = hechoHistoricos;
    }
   
    public int getIdCuantaLarga() {
        return this.idCuantaLarga;
    }
    
    public void setIdCuantaLarga(int idCuantaLarga) {
        this.idCuantaLarga = idCuantaLarga;
    }
    public GlifoG getGlifoG() {
        return this.glifoG;
    }
    
    public void setGlifoG(GlifoG glifoG) {
        this.glifoG = glifoG;
    }
    public KinCholqij getKinCholqij() {
        return this.kinCholqij;
    }
    
    public void setKinCholqij(KinCholqij kinCholqij) {
        this.kinCholqij = kinCholqij;
    }
    public KinHaab getKinHaab() {
        return this.kinHaab;
    }
    
    public void setKinHaab(KinHaab kinHaab) {
        this.kinHaab = kinHaab;
    }
    public Set getHechoHistoricos() {
        return this.hechoHistoricos;
    }
    
    public void setHechoHistoricos(Set hechoHistoricos) {
        this.hechoHistoricos = hechoHistoricos;
    }




}


