package proyectomayaprueba.Modelo;
// Generated 11/09/2019 02:29:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Energia generated by hbm2java
 */
public class Energia  implements java.io.Serializable {


     private int idEnergia;
     private Set kinCholqijs = new HashSet(0);

    public Energia() {
    }

	
    public Energia(int idEnergia) {
        this.idEnergia = idEnergia;
    }
    public Energia(int idEnergia, Set kinCholqijs) {
       this.idEnergia = idEnergia;
       this.kinCholqijs = kinCholqijs;
    }
   
    public int getIdEnergia() {
        return this.idEnergia;
    }
    
    public void setIdEnergia(int idEnergia) {
        this.idEnergia = idEnergia;
    }
    public Set getKinCholqijs() {
        return this.kinCholqijs;
    }
    
    public void setKinCholqijs(Set kinCholqijs) {
        this.kinCholqijs = kinCholqijs;
    }




}


