package proyectomayaprueba.Modelo;
// Generated 11/09/2019 02:29:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * KinHaab generated by hbm2java
 */
public class KinHaab  implements java.io.Serializable {


     private int idKinHaab;
     private DiaHaab diaHaab;
     private MesHaab mesHaab;
     private Set cuentaLargas = new HashSet(0);

    public KinHaab() {
    }

	
    public KinHaab(int idKinHaab, DiaHaab diaHaab, MesHaab mesHaab) {
        this.idKinHaab = idKinHaab;
        this.diaHaab = diaHaab;
        this.mesHaab = mesHaab;
    }
    public KinHaab(int idKinHaab, DiaHaab diaHaab, MesHaab mesHaab, Set cuentaLargas) {
       this.idKinHaab = idKinHaab;
       this.diaHaab = diaHaab;
       this.mesHaab = mesHaab;
       this.cuentaLargas = cuentaLargas;
    }
   
    public int getIdKinHaab() {
        return this.idKinHaab;
    }
    
    public void setIdKinHaab(int idKinHaab) {
        this.idKinHaab = idKinHaab;
    }
    public DiaHaab getDiaHaab() {
        return this.diaHaab;
    }
    
    public void setDiaHaab(DiaHaab diaHaab) {
        this.diaHaab = diaHaab;
    }
    public MesHaab getMesHaab() {
        return this.mesHaab;
    }
    
    public void setMesHaab(MesHaab mesHaab) {
        this.mesHaab = mesHaab;
    }
    public Set getCuentaLargas() {
        return this.cuentaLargas;
    }
    
    public void setCuentaLargas(Set cuentaLargas) {
        this.cuentaLargas = cuentaLargas;
    }




}


