package proyectomayaprueba.Modelo;
// Generated 11/09/2019 02:29:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MesHaab generated by hbm2java
 */
public class MesHaab  implements java.io.Serializable {


     private int idMesHaab;
     private Set kinHaabs = new HashSet(0);

    public MesHaab() {
    }

	
    public MesHaab(int idMesHaab) {
        this.idMesHaab = idMesHaab;
    }
    public MesHaab(int idMesHaab, Set kinHaabs) {
       this.idMesHaab = idMesHaab;
       this.kinHaabs = kinHaabs;
    }
   
    public int getIdMesHaab() {
        return this.idMesHaab;
    }
    
    public void setIdMesHaab(int idMesHaab) {
        this.idMesHaab = idMesHaab;
    }
    public Set getKinHaabs() {
        return this.kinHaabs;
    }
    
    public void setKinHaabs(Set kinHaabs) {
        this.kinHaabs = kinHaabs;
    }




}


