package proyectomayaprueba.Modelo;
// Generated 11/09/2019 02:29:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nahual generated by hbm2java
 */
public class Nahual  implements java.io.Serializable {


     private int idNahual;
     private Set kinCholqijs = new HashSet(0);

    public Nahual() {
    }

	
    public Nahual(int idNahual) {
        this.idNahual = idNahual;
    }
    public Nahual(int idNahual, Set kinCholqijs) {
       this.idNahual = idNahual;
       this.kinCholqijs = kinCholqijs;
    }
   
    public int getIdNahual() {
        return this.idNahual;
    }
    
    public void setIdNahual(int idNahual) {
        this.idNahual = idNahual;
    }
    public Set getKinCholqijs() {
        return this.kinCholqijs;
    }
    
    public void setKinCholqijs(Set kinCholqijs) {
        this.kinCholqijs = kinCholqijs;
    }




}


