
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 09 19:34:52 CST 2019
//----------------------------------------------------

package proyecto1compi1;

/** CUP generated class containing symbol constants. */
public class sym2 {
  /* terminals */
  public static final int DIAGONAL = 2;
  public static final int E_COMPONENTE = 18;
  public static final int PARAMETRO_ATRIBUTO_ETIQUETAS = 59;
  public static final int ALINEACION = 43;
  public static final int BORRAR_PAGINA = 26;
  public static final int PAGINA = 40;
  public static final int E_SITIO = 16;
  public static final int PARAMETROS = 10;
  public static final int PARAMETRO_URL = 51;
  public static final int PARAMETRO_IMAGEN = 56;
  public static final int NOMBRE = 8;
  public static final int ANCHO = 47;
  public static final int PATH = 32;
  public static final int PARAMETRO_ID = 49;
  public static final int ETIQUETAS = 12;
  public static final int E_HIJOS = 19;
  public static final int PARAMETRO_TODO_TEXTO = 60;
  public static final int IGUAL = 5;
  public static final int TITULO = 37;
  public static final int NOMBRE_ETIQUETA = 63;
  public static final int PARAMETRO_VIDEO = 57;
  public static final int PADRE = 39;
  public static final int PARAMETRO_FECHA = 52;
  public static final int ID = 31;
  public static final int NUEVA_PAGINA = 25;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 29;
  public static final int ATRIBUTO_ETIQUETAS = 48;
  public static final int CLASE = 41;
  public static final int error = 1;
  public static final int PARAMETRO_PATH = 50;
  public static final int ABRE = 3;
  public static final int PARAMETRO_ENTERO = 62;
  public static final int FECHA_MODIFICACION = 36;
  public static final int ATRIBUTOS = 15;
  public static final int BORRAR_SITIO_WEB = 24;
  public static final int ATRIBUTO = 14;
  public static final int ACCION = 6;
  public static final int COLOR = 44;
  public static final int FECHA_CREACION = 35;
  public static final int USUARIO_MODIFICACION = 34;
  public static final int PARAMETRO_MENU = 58;
  public static final int NUEVO_SITIO_WEB = 23;
  public static final int USUARIO_CREACION = 33;
  public static final int E_PAGINA = 22;
  public static final int VALOR = 13;
  public static final int E_HIJO = 20;
  public static final int E_COMPONENTES = 17;
  public static final int ORIGEN = 45;
  public static final int MODIFICAR_COMPONENTE = 30;
  public static final int PARAMETRO_PARRAFO = 55;
  public static final int PARAMETRO_TITULO = 54;
  public static final int PARAMETRO_ALINEACION = 61;
  public static final int AGREGAR_COMPONENTE = 28;
  public static final int PARAMETRO = 9;
  public static final int ACCIONES = 7;
  public static final int PARAMETRO_COLOR = 53;
  public static final int SITIO = 38;
  public static final int TEXTO = 42;
  public static final int ETIQUETA = 11;
  public static final int ALTURA = 46;
  public static final int CIERRA = 4;
  public static final int E_PAGINAS = 21;
  public static final int MODIFICAR_PAGINA = 27;
}

